mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/',include('todolist.urls'))
]

mysite/todolist/urls.py
from . import views
from django.urls import path
app_name = 'task'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:tid>',views.details,name='details'),
    # add task
    path('add', views.add , name="add"),
    # edit task
    path('edit/<int:id>' , views.edit , name="edit") ,
    #delete task
    path('delete/<int:id>' , views.delete , name="delete") , 

]

mysite/todolist/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    def __str__(self):
        return self.task_name
    task_name = models.CharField(max_length=200)
    task_desc = models.CharField(max_length=500)


mysite/todolist/forms.py
from dataclasses import field
from socket import fromshare
from django import forms
from . models import Task
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name' , 'task_desc']

mysite/todolist/views.py
from http.client import HTTPResponse
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import Task
from django.template import loader
from .forms import TaskForm

# Create your views here.
def index(request):
    task_list = Task.objects.all()
    #template = loader.get_template('todolist/index.html')
    context = {
        'task_list': task_list,
    }
    return render(request , 'todolist/index.html' , context)
def index(request):
    task_list = Task.objects.all()
    #template = loader.get_template('todolist/index.html')
    context = {
        'task_list': task_list,
    }
    return render(request , 'todolist/index.html' , context)

def details(request , tid):
    task = Task.objects.get(pk=tid)
    context = {
        'task':task,
    }
    #return HttpResponse(task.task_desc)
    return render(request , 'todolist/details.html', context)
def add(request):
    form = TaskForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('task:index')
    return render(request , 'todolist/task-form.html' , {'form':form})

def edit(request , id):
    task = Task.objects.get(pk=id)
    form = TaskForm(request.POST or None , instance=task)
    if form.is_valid():
        form.save()
        return redirect('task:index')
    return render(request , 'todolist/task-form.html',{'form':form , 'task':task})
def delete(request , id):
    task = Task.objects.get(pk=id)
    if request.method == "POST":
        task.delete()
    
        return redirect('task:index')
    return render(request , 'todolist/delete-task.html' , {'task':task})

mysite/todolist/templates/todolist/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Task App</a>
        <div class="navbar">
            <a class="nav-item" href="{% url 'task:add' %}">Add Task</a>
            &nbsp; &nbsp;&nbsp &nbsp;;
            <a class="nav-item" href="{% url 'task:index' %}">View Task</a>
                </div>
        </nav>
    {% block body %}
    {% endblock %}
    
</body>
</html>

mysite/todolist/templates/todolist/delete-task.html
{% extends 'todolist/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete-Task</title>
</head>
<body>
    {% block body %}
    <form method="POST" >
{%csrf_token%}
<h1>Are you Sure you want to delete this {{task.task_name}}?</h1>
<button type="Submit">Confirm</button>
{%endblock%}
</body>
</html>

mysite/todolist/templates/todolist/details.html
{% extends 'todolist/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Details</title>
</head>
<body>
    {% block body %}
<h1>{{task.task_name}} -  {{task.task_desc}}  <a href="{% url 'task:edit' task.id %}" class="btn btn-primary">Edit Task </a>  <a href="{% url 'task:delete' task.id %}" class="btn btn-danger">Delete Task </a></h1>
    {% endblock %}
</body>
</html>

mysite/todolist/templates/todolist/index.html
{% extends 'todolist/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Today</title>
</head>
<body>
    {% block body %}
    <ol>
        
        {% for task in task_list %}
        <li>
            <h3>
                <a href="{%url 'task:details' task.id %}">{{task}}</a>
            </h3>
        </li>
        {% endfor %}
        {% endblock %}
        </ol>
</body>
</html>

mysite/todolist/templates/todolist/task-form.html
{% extends 'todolist/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit">Add</button>
    </form>
    {% endblock %}
</body>

</html>